# Generated by Django 2.2.4 on 2019-09-07 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_publshed',
            new_name='is_published',
        ),
    ]
